In [14]:
import pandas as pd
import numpy as np

print("Libraries imported successfully")

Libraries imported successfully

In [15]:
movies = pd.read_csv("../data/raw/movies.csv")
ratings = pd.read_csv("../data/raw/ratings.csv")

print("Movies shape:", movies.shape)
print("Ratings shape:", ratings.shape)

Movies shape: (58098, 3)
Ratings shape: (27753444, 4)

In [16]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [17]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      307     3.5  1256677221
1       1      481     3.5  1256677456
2       1     1091     1.5  1256677471
3       1     1257     4.5  1256677460
4       1     1449     4.5  1256677264

In [18]:
print("Movies missing values:")
print(movies.isnull().sum())

print("\nRatings missing values:")
print(ratings.isnull().sum())

Movies missing values:
movieId    0
title      0
genres     0
dtype: int64

Ratings missing values:
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [19]:
print("Duplicate movies:", movies.duplicated().sum())
print("Duplicate ratings:", ratings.duplicated().sum())

Duplicate movies: 0
Duplicate ratings: 0

In [20]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 58098 entries, 0 to 58097
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  58098 non-null  int64
 1   title    58098 non-null  str
 2   genres   58098 non-null  str
dtypes: int64(1), str(2)
memory usage: 3.5 MB

In [21]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 27753444 entries, 0 to 27753443
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 847.0 MB

In [22]:
movies[movies.duplicated()]

Empty DataFrame
Columns: [movieId, title, genres]
Index: []

In [23]:
ratings[ratings.duplicated()]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

In [24]:
movies = movies.drop_duplicates()
ratings = ratings.drop_duplicates()

In [26]:
movies.to_csv(
    "../data/processed/movies_clean.csv",
    index=False
)

ratings.to_csv(
    "../data/processed/ratings_clean.csv",
    index=False
)

print("Cleaned datasets saved successfully!")

Cleaned datasets saved successfully!